#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the auto-loader
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and get the application
$app = require_once __DIR__.'/bootstrap/app.php';

// Handle the incoming console command
$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
